spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gmc
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: mindzen
  jpa:
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
logging:
  level:
    org.springframework.boot: INFO